modLoader = "javafml"
loaderVersion = "[21,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "neogenesis"
version = "${version}"
displayName = "NeoGenesis"
authors = "CamoBros4L, InvulnerableCaptain"
description = '''
A for of the original VS Genesis mod. Updated for Neoforge and Create Aeronautics!
'''
logoFile = "assets/genesis/icon.png"

[[dependencies.neogenesis]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neogenesis]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neogenesis]]
modId = "zps"
mandatory = true
versionRange = "[1.21.1-2.4.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neogenesis]]
modId = "sable"
mandatory = true
versionRange = "[2.0.3,]
side = "BOTH"

[[dependencies.neogenesis]]
modId = "lodestone"
mandatory = true
versionRange = "[1.21.1-1.8.2,)"
ordering = "NONE"
side = "CLIENT"
